version: "3"
services:
  app:
    build: .
    environment:
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
      - "8888:8888"
    restart: on-failure
    command: npm run start
